FROM apache/airflow:2.5.2-python3.9

USER root
RUN apt-get update && apt-get install -y git
USER airflow

RUN pip install -e git+https://github.com/astronomer/astronomer-cosmos@f48ed09cbc1eb29102ce23229ac34959f2d969df#egg=astronomer-cosmos

COPY dbt-requirements.txt ./
RUN pip install --no-cache-dir -r dbt-requirements.txt

COPY dags dags

ENV DBT_ROOT_PATH /opt/airflow/dags/dbt
ENV DBT_EXECUTABLE_PATH /home/airflow/.local/bin/dbt

